version: '3'
services:
  strapi:
    # image: strapi/strapi
    build: ./strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: gatsbybase
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: secret
    volumes: 
      - ./strapi:/usr/src/app
      - strapi_node_modules:/usr/src/app/node_modules
    ports:
      - '1337:1337'
    networks:
      - postgres_link
  web:
    build: ./web
    ports:
      - '8000:8000'
    volumes:
      - ./web:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules
    depends_on: 
      - strapi
    links:
      - "strapi:strapi"
    networks: 
      - postgres_link
volumes: 
  web_node_modules:
  strapi_node_modules:
networks:
  postgres_link:
    external:
      name: postgresql_default